# Generated by Django 3.1.5 on 2021-02-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210204_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='farmer',
            field=models.CharField(default='vishnu', max_length=100),
            preserve_default=False,
        ),
    ]
