# Generated by Django 3.1.5 on 2021-02-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jobs_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('date', models.DateField()),
                ('role', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cno', models.CharField(max_length=100)),
                ('farmer', models.CharField(max_length=100)),
            ],
        ),
    ]
