from django.urls import path
from . import views

urlpatterns = [
    path('home', views.home, name='home'),
    path('coconut', views.coconut, name='coconut'),
    path('tomato', views.tomato, name='tomato'),
    path('rice', views.rice, name='rice'),
    path('wheat', views.wheat, name='wheat'),
    path('bsr', views.bsr, name='bsr'),
    path('brnf', views.brnf, name='brnf'),
    path('cc', views.cc, name='cc'),
    path('gb', views.gb, name='gb'),
    path('lr', views.lr, name='lr'),
    path('lso', views.lso, name='lso'),
    path('ly', views.ly, name='ly'),
    path('ttr', views.ttr, name='ttr'),
    path('clr', views.clr, name='clr'),
    path('ecm', views.ecm, name='ecm'),
    path('ac', views.ac, name='ac'),
    path('ber', views.ber, name='ber'),
    path('fc', views.fc, name='fc'),
    path('lro', views.lro, name='lro'),
    path('sls', views.sls, name='sls'),
    path('ss', views.ss, name='ss'),
    path('blb', views.blb, name='blb'),
    path('bnn', views.bnn, name='bnn'),
    path('brs', views.brs, name='brs'),
    path('fs', views.fs, name='fs'),
    path('rb', views.rb, name='rb'),
    path('rgs', views.rgs, name='rgs'),
    path('sb', views.sb, name='sb'),
    path('rtbv', views.rtbv, name='rtbv'),
    path('lhph', views.lhph, name='lhph'),
    path('rbu', views.rbu, name='rbu'),
    path('sbo', views.sbo, name='sbo'),
    path('rgm', views.rgm, name='rgm'),
    path('bls', views.bls, name='bls'),
    path('bydv', views.bydv, name='bydv'),
    path('cbu', views.cbu, name='cbu'),
    path('ed', views.ed, name='ed'),
    path('es', views.es, name='es'),
    path('fhb', views.fhb, name='fhb'),
    path('pm', views.pm, name='pm'),
    path('lru', views.lru, name='lru'),
    path('aph', views.aph, name='aph'),
    path('aw', views.aw, name='aw'),
    path('sbu', views.sbu, name='sbu'),
    path('ww', views.ww, name='ww'),

]